version: '3'

services:

  # api
  api-spring-graphql:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api-spring-graphql
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgres:5432
      DATABASE_DB: "postgres"
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_SCHEMA: pocgraphql
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_EXPIRATION: 10000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  # database
  postgres:
    image: 'postgres:alpine'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # cache-redis
  redis:
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"